#!/bin/bash
 
# config
RSYNC=/usr/bin/rsync
SSH=/usr/bin/ssh
SSHPASS=/usr/bin/sshpass
PASSWORD=52df6c775c5ab791
USER=work
PORT=22
REMOTE_DIR=/data/www/iqg.com/current/app/logs/
#internalapi
#INTERNALAPI_REMOTE_DIR=/data/www/internal_api.com/shared/logs/　 #目前不传文件夹，只传指定文件

YESTERDAY1=`date -d 'yesterday' +'%Y%m%d'`
# YESTERDAY1=`date   +'%Y%m%d'`
echo $YESTERDAY1

INTERNALAPI_REMOTE_DIR=/data/www/internal_api.com/shared/logs/iqg_access_internal_api.log.$YESTERDAY1
echo $INTERNALAPI_REMOTE_DIR
 
HOST1=120.27.143.154
HOST2=114.55.86.65
# HOST3=120.27.192.210
HOST4=114.55.86.32
HOST5=114.55.38.248
HOST6=114.55.86.62
HOST7=114.55.86.92
HOST8=114.55.86.80


INTERNAL_LOCAL_DIR1=/ace/log/internal_api/server1/
INTERNAL_LOCAL_DIR2=/ace/log/internal_api/server2/
# INTERNAL_LOCAL_DIR3=/ace/log/internal_api/server3/
INTERNAL_LOCAL_DIR4=/ace/log/internal_api/server4/
INTERNAL_LOCAL_DIR5=/ace/log/internal_api/server5/
INTERNAL_LOCAL_DIR6=/ace/log/internal_api/server6/
INTERNAL_LOCAL_DIR7=/ace/log/internal_api/server7/
INTERNAL_LOCAL_DIR8=/ace/log/internal_api/server8/

 
# rsync+ssh+crontab command

# internalapi
$RSYNC -avzi -e "$SSHPASS -p $PASSWORD $SSH -p 5822" --delete $USER@$HOST1:$INTERNALAPI_REMOTE_DIR $INTERNAL_LOCAL_DIR1
#$RSYNC -avzi -e "$SSHPASS -p $PASSWORD $SSH -p $PORT" --delete $USER@$HOST2:$INTERNALAPI_REMOTE_DIR $INTERNAL_LOCAL_DIR2
 #$RSYNC -avzi -e "$SSHPASS -p $PASSWORD $SSH -p $PORT" --delete $USER@$HOST3:$INTERNALAPI_REMOTE_DIR $INTERNAL_LOCAL_DIR3
#$RSYNC -avzi -e "$SSHPASS -p $PASSWORD $SSH -p $PORT" --delete $USER@$HOST4:$INTERNALAPI_REMOTE_DIR $INTERNAL_LOCAL_DIR4
#$RSYNC -avzi -e "$SSHPASS -p $PASSWORD $SSH -p $PORT" --delete $USER@$HOST5:$INTERNALAPI_REMOTE_DIR $INTERNAL_LOCAL_DIR5
#$RSYNC -avzi -e "$SSHPASS -p $PASSWORD $SSH -p $PORT" --delete $USER@$HOST6:$INTERNALAPI_REMOTE_DIR $INTERNAL_LOCAL_DIR6
#$RSYNC -avzi -e "$SSHPASS -p $PASSWORD $SSH -p $PORT" --delete $USER@$HOST7:$INTERNALAPI_REMOTE_DIR $INTERNAL_LOCAL_DIR7
#$RSYNC -avzi -e "$SSHPASS -p $PASSWORD $SSH -p $PORT" --delete $USER@$HOST8:$INTERNALAPI_REMOTE_DIR $INTERNAL_LOCAL_DIR8